import Head from 'next/head'
import Image from 'next/image'
import Avatar from '../components/avatar'


export default function Home() {
    return ( 
      <div>
        <Head>
        <title > Google </title> 
        <meta name = "description"
        content = "Generated by create next app" / >
        <link rel = "icon"
        href = "/favicon.ico" / >
        </Head>


        { /* Header */ }

        <header className = "flex w-full p-5 justify-between text-sm text-grey-700" >

          { /* Left */ }

          <div className = "flex space-x-4 items-center" >
            <p className="link">About</p>
            <p className="link"> Store </p>
          </div>

          { /* Right */ }

          <div className = "flex space-x-4 items-center" >
            <p className="link"> Gmail </p> 
            <p className="link"> Images </p> 

            { /* Icon */ }

            { /* Avatar */ } 
            <Avatar url="https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.jaisonvladimirleroy.com%2F&psig=AOvVaw30wxBsKclWf7meWtNWppR0&ust=1632281114184000&source=images&cd=vfe&ved=2ahUKEwj01JKRj4_zAhWYxOAKHdL9BaEQr4kDegQIARAR" />

          </div> 
        </header>
        </div>
    )
}